Ext.require(['*']);Ext.ns('app','ux');Ext.define('Ext.app.PortalDropZone',{extend:'Ext.dd.DropTarget',constructor:function(portal,cfg){this.portal=portal;Ext.dd.ScrollManager.register(portal.body);Ext.app.PortalDropZone.superclass.constructor.call(this,portal.body,cfg);portal.body.ddScrollConfig=this.ddScrollConfig;},ddScrollConfig:{vthresh:50,hthresh:-1,animate:true,increment:200},createEvent:function(dd,e,data,col,c,pos){return{portal:this.portal,panel:data.panel,columnIndex:col,column:c,position:pos,data:data,source:dd,rawEvent:e,status:this.dropAllowed};},notifyOver:function(dd,e,data){var xy=e.getXY(),portal=this.portal,proxy=dd.proxy;if(!this.grid){this.grid=this.getGrid();}
var cw=portal.body.dom.clientWidth;if(!this.lastCW){this.lastCW=cw;}else if(this.lastCW!=cw){this.lastCW=cw;this.grid=this.getGrid();}
var colIndex=0,colRight=0,cols=this.grid.columnX,len=cols.length,cmatch=false;for(len;colIndex<len;colIndex++){colRight=cols[colIndex].x+cols[colIndex].w;if(xy[0]<colRight){cmatch=true;break;}}
if(!cmatch){colIndex--;}
var overPortlet,pos=0,h=0,match=false,overColumn=portal.items.getAt(colIndex),portlets=overColumn.items.items,overSelf=false;len=portlets.length;for(len;pos<len;pos++){overPortlet=portlets[pos];h=overPortlet.el.getHeight();if(h===0){overSelf=true;}else if((overPortlet.el.getY()+(h/2))>xy[1]){match=true;break;}}
pos=(match&&overPortlet?pos:overColumn.items.getCount())+(overSelf?-1:0);var overEvent=this.createEvent(dd,e,data,colIndex,overColumn,pos);if(portal.fireEvent('validatedrop',overEvent)!==false&&portal.fireEvent('beforedragover',overEvent)!==false){proxy.getProxy().setWidth('auto');if(overPortlet){dd.panelProxy.moveProxy(overPortlet.el.dom.parentNode,match?overPortlet.el.dom:null);}else{dd.panelProxy.moveProxy(overColumn.el.dom,null);}
this.lastPos={c:overColumn,col:colIndex,p:overSelf||(match&&overPortlet)?pos:false};this.scrollPos=portal.body.getScroll();portal.fireEvent('dragover',overEvent);return overEvent.status;}else{return overEvent.status;}},notifyOut:function(){delete this.grid;},notifyDrop:function(dd,e,data){delete this.grid;if(!this.lastPos){return;}
var c=this.lastPos.c,col=this.lastPos.col,pos=this.lastPos.p,panel=dd.panel,dropEvent=this.createEvent(dd,e,data,col,c,pos!==false?pos:c.items.getCount());if(this.portal.fireEvent('validatedrop',dropEvent)!==false&&this.portal.fireEvent('beforedrop',dropEvent)!==false){Ext.suspendLayouts();panel.el.dom.style.display='';dd.panelProxy.hide();dd.proxy.hide();if(pos!==false){c.insert(pos,panel);}else{c.add(panel);}
Ext.resumeLayouts(true);this.portal.fireEvent('drop',dropEvent);var st=this.scrollPos.top;if(st){var d=this.portal.body.dom;setTimeout(function(){d.scrollTop=st;},10);}}
delete this.lastPos;return true;},getGrid:function(){var box=this.portal.body.getBox();box.columnX=[];this.portal.items.each(function(c){box.columnX.push({x:c.el.getX(),w:c.el.getWidth()});});return box;},unreg:function(){Ext.dd.ScrollManager.unregister(this.portal.body);Ext.app.PortalDropZone.superclass.unreg.call(this);}});Ext.define('Ext.app.Portlet',{alias:'widget.portlet',extend:'Ext.panel.Panel',layout:'fit',anchor:'100%',frame:true,closable:true,collapsible:true,animCollapse:true,draggable:{moveOnDrag:false},cls:'x-portlet',doClose:function(){if(!this.closing){this.closing=true;this.el.animate({opacity:0,callback:function(){this.fireEvent('close',this);this[this.closeAction]();},scope:this});}}});Ext.define('Ext.app.PortalColumn',{extend:'Ext.container.Container',alias:'widget.portalcolumn',requires:['Ext.layout.container.Anchor','Ext.app.Portlet'],layout:'anchor',defaultType:'portlet',cls:'x-portal-column'});Ext.define('Ext.app.PortalPanel',{extend:'Ext.panel.Panel',alias:'widget.portalpanel',requires:['Ext.layout.container.Column','Ext.app.PortalDropZone','Ext.app.PortalColumn'],cls:'x-portal',bodyCls:'x-portal-body',defaultType:'portalcolumn',autoScroll:true,manageHeight:false,initComponent:function(){var me=this;this.layout={type:'column'};this.callParent();this.addEvents({validatedrop:true,beforedragover:true,dragover:true,beforedrop:true,drop:true});this.on('drop',this.doLayout,this);},beforeLayout:function(){var items=this.layout.getLayoutItems(),len=items.length,i=0,firstAndLast=['x-portal-column-first','x-portal-column-last'],item;for(;i<len;i++){item=items[i];item.removeCls(['x-portal-column-first','x-portal-column-last']);}
items[0].addCls('x-portal-column-first');items[len-1].addCls('x-portal-column-last');return this.callParent(arguments);},initEvents:function(){this.callParent();this.dd=Ext.create('Ext.app.PortalDropZone',this,this.dropConfig);},beforeDestroy:function(){if(this.dd){this.dd.unreg();}
this.callParent();}});Ext.define('Ext.ux.IFrame',{extend:'Ext.Component',alias:'widget.uxiframe',loadMask:'Loading...',src:'about:blank',renderTpl:['<iframe src="{src}" name="{frameName}" width="100%" height="100%" frameborder="0"></iframe>'],initComponent:function(){this.callParent();this.frameName=this.frameName||this.id+'-frame';this.addEvents('beforeload','load');Ext.apply(this.renderSelectors,{iframeEl:'iframe'});},initEvents:function(){var me=this,iframeEl=me.iframeEl.dom,frameEl=me.getFrame();me.callParent();me.iframeEl.on('load',me.onLoad,me);},initRenderData:function(){return Ext.apply(this.callParent(),{src:this.src,frameName:this.frameName});},getBody:function(){var doc=this.getDoc();return doc.body||doc.documentElement;},getDoc:function(){try{return this.getWin().document;}catch(ex){return null;}},getWin:function(){var me=this,name=me.frameName,win=Ext.isIE?me.iframeEl.dom.contentWindow:window.frames[name];return win;},getFrame:function(){var me=this;return me.iframeEl.dom;},beforeDestroy:function(){var me=this,doc,prop;if(me.rendered){try{doc=me.getDoc();if(doc){Ext.EventManager.removeAll(doc);for(prop in doc){if(doc.hasOwnProperty&&doc.hasOwnProperty(prop)){delete doc[prop];}}}}catch(e){}}
me.callParent();},onLoad:function(){var me=this,doc=me.getDoc(),fn=me.onRelayedEvent;if(doc){try{Ext.EventManager.removeAll(doc);Ext.EventManager.on(doc,{mousedown:fn,mousemove:fn,mouseup:fn,click:fn,dblclick:fn,scope:me});}catch(e){}
Ext.EventManager.on(window,'unload',me.beforeDestroy,me);this.el.unmask();this.fireEvent('load',this);}else if(me.src&&me.src!=''){this.el.unmask();this.fireEvent('error',this);}},onRelayedEvent:function(event){var iframeEl=this.iframeEl,iframeXY=iframeEl.getXY(),eventXY=event.getXY();event.xy=[iframeXY[0]+eventXY[0],iframeXY[1]+eventXY[1]];event.injectEvent(iframeEl);event.xy=eventXY;},load:function(src){var me=this,text=me.loadMask,frame=me.getFrame();if(me.fireEvent('beforeload',me,src)!==false){if(text&&me.el){me.el.mask(text);}
frame.src=me.src=(src||me.src);}}});