Ext.define('LargeScaleApp.model.Customer', {
    extend: 'Ext.data.Model',
    fields: [
        { name: 'id', type: 'int' },
        { name: 'firstName', type: 'string' },
        { name: 'lastName', type: 'string' },
        { name: 'email', type: 'string' },
        { name: 'phone', type: 'string' },
        { name: 'addressLine1', type: 'string' },
        { name: 'addressLine2', type: 'string' },
        { name: 'city', type: 'string' },
        { name: 'state', type: 'string' },
        { name: 'zipCode', type: 'string' },
        { name: 'country', type: 'string' },
        { name: 'createdDate', type: 'date', dateFormat: 'c' },
        { name: 'lastUpdated', type: 'date', dateFormat: 'c' },
        { name: 'isActive', type: 'boolean' },
        { name: 'dateOfBirth', type: 'date', dateFormat: 'c' },
        { name: 'gender', type: 'string' },
        { name: 'occupation', type: 'string' },
        { name: 'companyName', type: 'string' },
        { name: 'annualIncome', type: 'float' },
        { name: 'customerType', type: 'string' },
        { name: 'loyaltyPoints', type: 'int' },
        { name: 'lastPurchaseDate', type: 'date', dateFormat: 'c' },
        { name: 'newsletterSubscribed', type: 'boolean' },
        { name: 'preferredContactMethod', type: 'string' },
        { name: 'accountStatus', type: 'string' },
        { name: 'creditLimit', type: 'float' },
        { name: 'billingAddress', type: 'string' },
        { name: 'shippingAddress', type: 'string' },
        { name: 'taxId', type: 'string' },
        { name: 'customerSegment', type: 'string' },
        { name: 'registrationDate', type: 'date', dateFormat: 'c' },
        { name: 'lastLoginDate', type: 'date', dateFormat: 'c' },
        { name: 'preferredLanguage', type: 'string' },
        { name: 'timeZone', type: 'string' },
        { name: 'notes', type: 'string' },
        { name: 'emergencyContact', type: 'string' },
        { name: 'emergencyPhone', type: 'string' },
        { name: 'referralSource', type: 'string' },
        { name: 'socialMediaHandle', type: 'string' },
        { name: 'website', type: 'string' },
        { name: 'fax', type: 'string' },
        { name: 'isVerified', type: 'boolean' },
        { name: 'verificationDate', type: 'date', dateFormat: 'c' },
        { name: 'lastContacted', type: 'date', dateFormat: 'c' },
        { name: 'customerRating', type: 'float' }
    ]
});