export interface CustomerDto {
  id: number;
  firstName: string | null;
  lastName: string | null;
  email: string | null;
  phone: string | null;
  addressLine1: string | null;
  addressLine2: string | null;
  city: string | null;
  state: string | null;
  zipCode: string | null;
  country: string | null;
  createdDate: string;
  lastUpdated: string;
  isActive: boolean;
  dateOfBirth: string | null;
  gender: string | null;
  occupation: string | null;
  companyName: string | null;
  annualIncome: number;
  customerType: string | null;
  loyaltyPoints: number;
  lastPurchaseDate: string | null;
  newsletterSubscribed: boolean;
  preferredContactMethod: string | null;
  accountStatus: string | null;
  creditLimit: number;
  billingAddress: string | null;
  shippingAddress: string | null;
  taxId: string | null;
  customerSegment: string | null;
  registrationDate: string | null;
  lastLoginDate: string | null;
  preferredLanguage: string | null;
  timeZone: string | null;
  notes: string | null;
  emergencyContact: string | null;
  emergencyPhone: string | null;
  referralSource: string | null;
  socialMediaHandle: string | null;
  website: string | null;
  fax: string | null;
  isVerified: boolean;
  verificationDate: string | null;
  lastContacted: string | null;
  customerRating: number;
}
